# Icinga2 Deployment

networks:
  icinga2_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16

services:

  icinga2:
    build:
      context: ./icinga2
      dockerfile: Dockerfile
    image: core-icinga2:latest
    container_name: icinga2-core
    hostname: icinga2
    restart: unless-stopped
    ports:
      - "5665:5665"
    volumes:
      - icinga2-etc:/etc/icinga2
      - icinga2-lib:/var/lib/icinga2
      - icinga2-log:/var/log/icinga2
      - icinga2-cache:/var/cache/icinga2
      - icinga2-spool:/var/spool/icinga2
    networks:
      icinga2_network:
        ipv4_address: 172.31.0.2

  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: pg17-icinga2:latest              # will be built automatically
    container_name: icinga2-postgresql
    restart: unless-stopped
    # Change these passwords in production!
    environment:
      POSTGRES_PASSWORD: postgres          # superuser password
      # If you ever want a different default DB/user, uncomment:
      # POSTGRES_USER: postgres
      # POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      icinga2_network:
        ipv4_address: 172.31.0.5

volumes:
  icinga2-etc:
  icinga2-lib:
  icinga2-log:
  icinga2-cache:
  icinga2-spool: